#!/bin/bash
# log file should be the command-line argument.

foamLog ${1} >/dev/null

# gnuplot -persist > /dev/null 2>&1 << EOF

gnuplot -persist << EOF
  set key opaque
  set logscale y
  set title "Residual vs. Iteration"
  set xlabel "Iteration"
  set ylabel "Residual"
  set term png
  set output "residuals.png"

  plot "logs/Ux_0" with lines,\
    "logs/Uy_0" with lines,\
    "logs/k_0" with lines,\
    "logs/epsilon_0" with lines,\
    "logs/rho_0" with lines,\
    "logs/p_0" with lines
EOF
